### ISSUE TITLE
RL Zoo?

### ISSUE THREAD

**Issue by araffin** [tboulet/StableBaselines3FullPipeline#1]
Hello,
nice project =)
Related to https://github.com/DLR-RM/stable-baselines3/issues/1254, are you aware of the RL Zoo: https://github.com/DLR-RM/rl-baselines3-zoo ?
(looking at the naming convention, I would say yes)

If yes, what was missing/preventing you from using/extending it?

**Comment by tboulet** [comment]
Hey thank you !

I've heard of the RL Zoo yes but for my projects I've always only needed the basic library, so I havn't made the effort to look at RL Zoo and its documentation.

Concerning this repo, I wanted to learn the library by myself at a lower level.

But yes actually the RL Zoo looks very great in terms of feature, I would probably use it for serious applied RL projects and perhaps benchmarks.

**Comment by araffin** [comment]
> Concerning this repo, I wanted to learn the library by myself at a lower level.

make sense, thanks for the answer =)
